locale = "pt-br"
label = "Português"
weight = 1
title = "Studio Bravarda"

[params]
  displayName = "Português"
  isoCode = "pt-br"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "/img/logo.png"

[params.author]
  name = "Obrigado por tudo!"
  headline = "2020 - 2026"
