disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Thank you for everything!"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
author = { name = "THANK YOU FOR EVERYTHING!" }
logo = "Logo Bravarda.png"
