[[main]]
none = "none"

[[main]]
name = "Sky Caravan"
# parent = "Portfolio"
pageRef = "sky-caravan"
weight = 1

[[main]]
name = "Extremely Powerful Capybaras"
# parent = "Portfolio"
pageRef = "extremely-powerful-capybaras"
weight = 2

[[main]]
name = "Presskit"
pageRef = "presskit"
identifier = "N0Wbh1Qf3h"
weight = 3
