colorScheme = "bravarda"
defaultAppearance = "dark"
autoSwitchAppearance = "false"
enableSearch = false
enableCodeCopy = false
replyByEmail = false
disableImageOptimization = false
disableTextInHeader = true
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
defaultFeaturedImage = "header_banner.png"
defaultBackgroundImage = "."
firebase = { }
fathomAnalytics = { }
umamiAnalytics = { }
selineAnalytics = { }
buymeacoffee = { }
verification = { }
disableImageZoom = true

[header]
layout = "basic"

[author]
name = "Studio Bravarda"
headline = "2020 - 2026"
links = [ ]

[footer]
showMenu = false
showCopyright = false
showThemeAttribution = false
showAppearanceSwitcher = false
showScrollToTop = false

[homepage]
layout = "background"
showRecent = false
showRecentItems = 5
showMoreLink = false
showMoreLinkDest = "/posts/"
cardView = false
cardViewScreenWidth = ""
layoutBackgroundBlur = false
homepageImage = "img/background.png"

[article]
showDate = false
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = false
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = false
invertPagination = false
showReadingTime = false
showTableOfContents = false
showTaxonomies = true
showAuthorsBadges = false
showWordCount = false
showZenMode = false
heroStyle = "thumbAndBackground"
showRelatedContent = false
relatedContentLimit = "0"

[list]
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
orderByWeight = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false
